mongo_db: "jongleur"
mongo_endpoint: "mongodb://localhost:27017/"
redis_endpoint: "redis://localhost:6379"
jwt_private_key: ./res/jongleur_jwt_key_private.der
jwt_public_key: ./res/jongleur_jwt_key_pub.der
jwt_public_key_pem: ./res/jongleur_jwt_key_pub.pem